{% set name = "robocorp-storage" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_storage-{{ version }}.tar.gz
  sha256: f584e3a17d5e92e35655947643e69b6501883ae36a53c17950c76529b193d13b

build:
  noarch: python
  script: 
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7.2,<4.0.0
    - requests >=2.28.2,<3.0.0
    - tenacity >=8.0.1,<9.0.0
    - typing-extensions >=4.6.3,<5.0.0

test:
  imports:
    - robocorp.storage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp Asset Storage library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
